#------------------------------------------------------------------------------------
# DEseq2.R
#
# This script is used after generating read counts 
# for genes using featureCounts.
#
# Identify genes differentially expressed between
# species at a particular developmental stage (2dpf or 8dpf)
#
# example output: https://github.com/joemcgirr/fishfASE/blob/master/examples/de_genes_8dpf_gff.txt
#
#------------------------------------------------------------------------------------

# sample metadata 
samples <- read.table("sample_metadata.txt", header = TRUE, stringsAsFactors = FALSE, sep = "\t")
#remove hybrids and test 8dpf stage
samples <- filter(samples, species != "h") %>% filter(stage == "8dpf")

# read counts for all genes generated by featureCounts
cts <- read.table("counts_all_feature_types_gff.txt",row.names=1, header = TRUE, stringsAsFactors = FALSE, sep = "\t")
cts <- cts[samples$sample]
row.names(samples) <- samples$sample
samples$sample <- NULL

cts <- as.matrix(cts) 
colData <- as.matrix(samples)

# create DESeq object
dds <- DESeqDataSetFromMatrix(countData = cts,
                              colData = colData,
                              design= ~p_unique)
dds <- estimateSizeFactors(dds)
idx <- rowSums(counts(dds, normalized=TRUE) >= 1 ) >= 1
length(rowSums(counts(dds, normalized=TRUE) >= 1 ) >= 1)
length(idx)
dds <- dds[idx,]
dds <- DESeq(dds)

# normalized counts
norm_cts <- data.frame(counts(dds, normalized=TRUE))
norm_cts$GeneID <- row.names(norm_cts)

# Identify genes DE between species at 0.01 significance
res <- results(dds, alpha=0.01)
resOrdered <- res[order(res$padj),]

res_ordered <- as.data.frame(resOrdered)
res_ordered$Geneid <- rownames(res_ordered)

# summary of DE genes
total_genes <- nrow(res_ordered)
de_total    <- nrow(res_ordered[which(res_ordered$padj < 0.01),])
de_up       <- (nrow(res_ordered[which(res_ordered$log2FoldChange > 0 & res_ordered$padj < 0.01),]))/total_genes
de_dn       <- (nrow(res_ordered[which(res_ordered$log2FoldChange < 0 & res_ordered$padj < 0.01),]))/total_genes
prop_de     <- de_total/total_genes


write.table(res_ordered, "de_genes_8dpf_gff.txt", row.names = FALSE, quote= FALSE,sep="\t")